apiVersion: batch/v1
kind: Job
metadata:
  name: new-ttt-job
spec:
  template:
    spec:
      containers:
      - name: new-ttt-job
        image: yash5090/new-ttt:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
