apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-ttt-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: new-ttt
  template:
    metadata:
      labels:
        app: new-ttt
    spec:
      containers:
        - name: new-ttt
          image: yash5090/new-ttt:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
